include core/arch/arm/cpu/cortex-armv8-0.mk

$(call force,CFG_8250_UART,y)
$(call force,CFG_GENERIC_BOOT,y)
$(call force,CFG_GIC,y)
$(call force,CFG_ARM_GICV3,y)
$(call force,CFG_PM_STUBS,y)
$(call force,CFG_SECURE_TIME_SOURCE_CNTPCT,y)

ifeq ($(PLATFORM_FLAVOR),a55)
$(call force,CFG_TEE_CORE_NB_CORE,8)
$(call force,CFG_WITH_ARM_TRUSTED_FW,y)
$(call force,CFG_ARM64_core,y)
$(call force,CFG_WITH_ARM_TRUSTED_FW,y)
$(call force,CFG_WITH_LPAE,y)
else
$(error Unsupported PLATFORM_FLAVOR "$(PLATFORM_FLAVOR)")
endif

ifeq ($(PLATFORM_FLAVOR),a55)
PHYS_SDRAM_1 = 0x80000000
PHYS_SDRAM_1_SIZE = 0x80000000
CFG_KERNEL_MEM_SIZE ?= 0x68000000

CFG_TZDRAM_START = $(PHYS_SDRAM_1)
CFG_TZDRAM_SIZE ?= (12 * 1024 * 1024)

CFG_SHMEM_START ?= ($(CFG_TZDRAM_START) + $(CFG_TZDRAM_SIZE))
CFG_SHMEM_SIZE ?= (2 * 1024 *1024)

CFG_DYNM_FROM_KERNEL ?= y
CFG_DYNM_KERNEL_START ?= (${CFG_SHMEM_START}+${CFG_SHMEM_SIZE})
CFG_DYNM_KERNEL_SIZE ?= (${CFG_KERNEL_MEM_SIZE}-($(CFG_DYNM_KERNEL_START)-$(PHYS_SDRAM_1)))

CFG_CHECK_STAGE2_MMU ?= y
CFG_STAGE2_MMU_START ?= ($(PHYS_SDRAM_1) + 0x6a000000)
CFG_STAGE2_MMU_SIZE ?= 0x500000

CFG_NUM_THREADS ?= 8
endif

CFG_CRYPTO_WITH_CE ?= n
CFG_WITH_STACK_CANARIES ?= y
CFG_TEE_CORE_EMBED_INTERNAL_TESTS ?= y
CFG_WITH_STACK_CANARIES ?= y
CFG_WITH_STATS ?= y
CFG_MMAP_REGIONS ?= 20
